// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ImageController from "./image_controller"
application.register("image", ImageController)

import SignupController from "./signup_controller"
application.register("signup", SignupController)

import Notification from "stimulus-notification"
application.register("notification", Notification)

import PasswordVisibility from "stimulus-password-visibility"
application.register("password-visibility", PasswordVisibility)
