require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "node_modules/**/*"

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/development.rb"

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
